project:
  type: website

website:
  title: "TLG Treasury"
  site-url: https://frankk1999.github.io/tlg-treasury/
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    - id: sidebar
      style: docked
      collapse-level: 1
      border: true
      contents:
        - file: index.qmd
          text: Introduction
        - text: "---"
        - auto: tables
        - auto: listings
        - auto: graphs
        - text: "---"
        - text: |
            <div class="sidebar-author">
              <span>Author: Frank Yang</span>
              <a href="https://www.linkedin.com/in/frank-yang-192559236/" target="_blank">
                <i class="bi bi-linkedin"></i>
              </a>
            </div>

format:
  html:
    theme: darkly
    toc: true
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
    page-layout: article
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
